apiVersion: v1
kind: ConfigMap
metadata:
  name: krunker-config
  namespace: krunker
data:
  NODE_ENV: production
  AUTH_STORE: postgres
  HOST: 0.0.0.0
  PORT: "2567"
  DATABASE_POOL_MAX: "4"
  PUBLIC_ORIGIN: https://krunker.raphcvr.me
